#!/usr/bin/env bash
set -euo pipefail

if [ ! $# -eq 1 ]; then
  echo 'Usage: mksh script_name [editor]' 1>&2
  exit 1
elif [ -e "$1" ]; then
  echo "$1 already exists" 1>&2
  exit 1
fi

echo '#!/usr/bin/env bash
set -euo pipefail

' > "$1"

chmod u+x "$1"

EDITOR=${2:-vim}
"$EDITOR" "$1"
